param(
    [string]$FabOSDir = "C:\FabVex\FabOS",
    [string]$FabOSWebDir = "C:\FabVex\FabOS-Web",
    [string]$CaddyDir = "C:\FabVex\Server",
    [string]$DataDir = "C:\FabVex\Data",
    [string]$Domain = "fabvex.duckdns.org",
    [switch]$SkipBuild,
    [switch]$SkipServices
)

$ErrorActionPreference = "Stop"

function Require-Path($Path, $Label) {
    if (-not (Test-Path -LiteralPath $Path)) { throw "$Label was not found: $Path" }
}

function Prompt-Value([string]$Label, [string]$Default) {
    $value = Read-Host "$Label [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}

Write-Host ""
Write-Host "============================================="
Write-Host " FABVEX PRODUCTION SETUP"
Write-Host "============================================="
Write-Host "This prepares the Windows host for FabOS + FabOS-Web."
Write-Host "It does not create Stripe credentials or expose the API directly."
Write-Host ""

$FabOSDir = Prompt-Value "FabOS directory" $FabOSDir
$FabOSWebDir = Prompt-Value "FabOS-Web directory" $FabOSWebDir
$CaddyDir = Prompt-Value "Caddy/server directory" $CaddyDir
$DataDir = Prompt-Value "Persistent FabOS data directory" $DataDir
$Domain = Prompt-Value "Public hostname" $Domain

Require-Path $FabOSDir "FabOS directory"
Require-Path $FabOSWebDir "FabOS-Web directory"
Require-Path (Join-Path $FabOSDir "fabos_api\server.py") "FabOS API"
Require-Path (Join-Path $FabOSWebDir "package.json") "FabOS-Web package.json"
Require-Path $CaddyDir "Caddy/server directory"
Require-Path (Join-Path $CaddyDir "caddy.exe") "Caddy executable"

New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
$deploymentDir = Join-Path $FabOSWebDir "deployment\windows"
$envFile = Join-Path $deploymentDir "server.env"
$caddySource = Join-Path $deploymentDir "Caddyfile"
$caddyTarget = Join-Path $CaddyDir "Caddyfile"

if (-not $SkipBuild) {
    Push-Location $FabOSWebDir
    try {
        Write-Host "Installing frontend dependencies..."
        npm ci
        if ($LASTEXITCODE -ne 0) { throw "npm ci failed." }
        Write-Host "Building production storefront..."
        npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed." }
    } finally {
        Pop-Location
    }
}

$envLines = @(
    "# Generated by Setup-FabVex.ps1. Keep this file private.",
    "FABOS_DATA_DIR=$DataDir",
    "FABOS_API_HOST=127.0.0.1",
    "FABOS_API_PORT=8000",
    "FABOS_API_THREADS=8",
    "FABOS_PAYMENT_PROVIDER=stripe",
    "FABOS_API_ALLOW_ORIGIN=https://$Domain",
    "FABOS_API_DOCS=false",
    "# Add live/test Stripe credentials only after creating and verifying the Stripe account.",
    "STRIPE_SECRET_KEY=",
    "STRIPE_WEBHOOK_SECRET=",
    "STRIPE_SUCCESS_URL=https://$Domain/orders.html",
    "STRIPE_CANCEL_URL=https://$Domain/checkout.html",
    "# Optional DuckDNS updater configuration.",
    "DUCKDNS_DOMAIN=",
    "DUCKDNS_TOKEN=",
    "# Optional AI configuration. AI remains disabled until explicitly enabled in FabOS settings.",
    "FABOS_AI_API_KEY="
)
$envLines -join [Environment]::NewLine | Set-Content -LiteralPath $envFile -Encoding UTF8

$caddy = Get-Content -LiteralPath $caddySource -Raw
$caddy = $caddy -replace '(?m)^fabvex\.duckdns\.org \{', "$Domain {"
$caddy = $caddy -replace 'C:\\FabVex\\FabOS-Web\\dist', (($FabOSWebDir -replace '\\','\') + "\dist")
$caddy = $caddy -replace 'C:\\FabVex\\Server\\logs', (($CaddyDir -replace '\\','\') + "\logs")
$caddy = $caddy -replace '(?m)^\s*root \* .*$', ("    root * " + (Join-Path $FabOSWebDir "dist"))
$caddy = $caddy -replace '(?m)^\s*output file .*caddy-access\.log', ("        output file " + (Join-Path $CaddyDir "logs\caddy-access.log"))
$caddy | Set-Content -LiteralPath $caddyTarget -Encoding UTF8

Write-Host "Validating Caddy configuration..."
& (Join-Path $CaddyDir "caddy.exe") validate --config $caddyTarget
if ($LASTEXITCODE -ne 0) { throw "Caddy validation failed." }

icacls.exe $envFile /inheritance:r /grant:r "SYSTEM:F" "Administrators:F" | Out-Null

Write-Host ""
Write-Host "Configuration created:"
Write-Host "  Domain:     $Domain"
Write-Host "  Data:       $DataDir"
Write-Host "  Env file:   $envFile"
Write-Host "  Caddyfile:  $caddyTarget"
Write-Host ""

if (-not $SkipServices) {
    $installer = Join-Path $deploymentDir "Install-FabVex-Services.ps1"
    Require-Path $installer "FabVex service installer"
    & $installer -FabOSDir $FabOSDir -FabOSWebDir $FabOSWebDir -CaddyDir $CaddyDir -DataDir $DataDir -EnvFile $envFile
}

Write-Host ""
Write-Host "SETUP COMPLETE"
Write-Host "Next:"
Write-Host "  1. Configure DNS/router or Cloudflare Tunnel for $Domain."
Write-Host "  2. Run the first-start owner setup in FabOS and change the bootstrap password."
Write-Host "  3. Open Administration > Business Settings and select the business/tax state."
Write-Host "  4. Open Administration > Marketing & Sales and enable only the marketplaces you use."
Write-Host "  5. Add marketplace credentials only after creating those accounts."
Write-Host "  6. Configure shipping, tax, catalog visibility and printers."
Write-Host "  7. Add Stripe test credentials and configure the webhook before live payments."
Write-Host "  8. Run the production acceptance/recovery checklist."
