import React,{useEffect,useState} from 'react'
import {Activity,AlertTriangle,Box,Check,CheckCircle2,Clock3,FileText,LogOut,Moon,Package,Printer,RefreshCw,Settings2,ShoppingBag,Sun,Users,X} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {createAdminCustomer,createAdminProof,getAdminProofs,getAdminQuotes,getOperationsDashboard,loginTeam,logoutCustomer,runOperationsAutomation,startAdminProduction,updateAdminQuote,uploadAdminProof} from './api.js'
import {getTheme,setTheme} from './theme.js'
import './admin.css'
const money=c=>(Number(c||0)/100).toLocaleString(undefined,{style:'currency',currency:'USD'})
const pct=r=>(Number(r?.initial_g||0)>0?Math.max(0,Math.min(100,Number(r.remaining_g||0)/Number(r.initial_g)*100)):0)
const quoteStatus={draft:'Submitted',under_review:'Under review',sent:'Awaiting customer',accepted:'Accepted',approved:'Accepted',declined:'Declined',expired:'Expired'}
function Login({onLogin,error,setError}){const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await loginTeam(identifier,password))}catch(err){setError(err.message||'Unable to sign in.')}finally{setBusy(false)}};return <main className="admin-login"><div className="admin-login-card"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><p className="admin-kicker">PRIVATE TEAM ACCESS</p><h1>Business command center.</h1><p className="admin-muted">Production, printers, quotes, orders, inventory, and business activity in one protected view.</p><form onSubmit={submit}><label>Username or email<input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="admin-error">{error}</div>}<button className="admin-primary" disabled={busy}>{busy?'Signing in…':'Open FabOS Dashboard'}</button></form></div></main>}
function Metric({icon:Icon,label,value,sub,alert}){return <div className={alert?'metric alert':'metric'}><div className="metric-icon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Dashboard({session,onLogout}){const [data,setData]=useState(null),[quotes,setQuotes]=useState([]),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false),[automating,setAutomating]=useState(false),[modal,setModal]=useState(null),[message,setMessage]=useState(''),[theme,setThemeState]=useState(getTheme());const [customer,setCustomer]=useState({name:'',email:'',phone:'',notes:''}),[orderId,setOrderId]=useState(''),[proofQuoteId,setProofQuoteId]=useState(''),[proofs,setProofs]=useState([]),[proofNotes,setProofNotes]=useState(''),[proofFile,setProofFile]=useState(null),[proofBusy,setProofBusy]=useState(false)
 const load=async()=>{setRefreshing(true);try{const [dashboard,qs]=await Promise.all([getOperationsDashboard(),getAdminQuotes()]);setData(dashboard);setQuotes(qs);setError('')}catch(e){setError(e.message||'Dashboard unavailable.')}finally{setRefreshing(false)}}
 useEffect(()=>{load();const id=setInterval(load,10000);return()=>clearInterval(id)},[])
 const runAutomation=async()=>{setAutomating(true);try{await runOperationsAutomation();await load()}catch(e){setError(e.message||'Automation run failed.')}finally{setAutomating(false)}}
 const sendQuote=async id=>{try{await updateAdminQuote(id,{status:'sent'});setMessage('Quote approved and sent to the customer.');await load()}catch(e){setError(e.message||'Quote could not be sent.')}}
 const addCustomer=async e=>{e.preventDefault();try{await createAdminCustomer(customer);setMessage('Customer added.');setCustomer({name:'',email:'',phone:'',notes:''});setModal(null)}catch(err){setError(err.message||'Customer could not be added.')}}
 const openProof=async quoteId=>{setProofQuoteId(quoteId);setProofNotes('');setProofFile(null);setProofs([]);setModal('proof');try{setProofs(await getAdminProofs(quoteId))}catch(e){setError(e.message||'Proofs could not be loaded.')}}
 const sendCurrentProof=async()=>{setProofBusy(true);try{const result=await createAdminProof(proofQuoteId,{notes:proofNotes,send:true});setProofs(await getAdminProofs(proofQuoteId));setMessage('Current design proof sent to the customer.');setProofNotes('');}catch(e){setError(e.message||'Proof could not be sent.')}finally{setProofBusy(false)}}
 const uploadProof=async e=>{e.preventDefault();if(!proofFile)return;setProofBusy(true);try{await uploadAdminProof(proofQuoteId,proofFile,proofNotes);setProofs(await getAdminProofs(proofQuoteId));setMessage('New proof uploaded and sent to the customer.');setProofFile(null);setProofNotes('');e.target.reset()}catch(err){setError(err.message||'Proof upload failed.')}finally{setProofBusy(false)}}
 const startProduction=async e=>{e.preventDefault();try{const result=await startAdminProduction(orderId.trim());setMessage(result.jobs_created?.length?'Production jobs created.':'Production is already queued or needs payment/confirmation.');setOrderId('');setModal(null);await load()}catch(err){setError(err.message||'Production could not be started.')}}
 if(error&&!data)return <div className="admin-shell"><header className="admin-header"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><button className="admin-ghost" onClick={onLogout}>Sign out</button></header><div className="admin-error-panel">{error}<button onClick={load}>Retry</button></div></div>
 const d=data||{business:{},production:{automation:{},jobs:[]},printers:{items:[],online:0,total:0},inventory:{spools:[],low_filament:0,low_supplies:0},maintenance:{items:[]},recent_orders:[],action_items:[]}
 return <><div className="admin-shell"><header className="admin-header"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><div className="admin-header-right"><span className="live-dot">● LIVE</span><span>{session?.user?.name||session?.user?.email||'Team'}</span><button className="admin-icon" onClick={()=>{const next=theme==='dark'?'light':'dark';setTheme(next);setThemeState(next)}} aria-label="Toggle theme">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><button className="admin-icon" onClick={load} disabled={refreshing} aria-label="Refresh"><RefreshCw size={17} className={refreshing?'spin':''}/></button><button className="admin-ghost" onClick={onLogout}><LogOut size={15}/> Sign out</button></div></header>
 <div className="admin-layout"><aside className="admin-sidebar"><a className="active" href="#overview">Overview</a><a href="#quotes">Quotes</a><a href="#orders">Orders</a><a href="#production">Production</a><a href="#printers">Printers</a><a href="#customers" onClick={()=>setModal('customer')}>Customers</a><a href="#inventory">Materials</a><a href="#settings">Settings</a></aside>
 <main className="admin-main" id="overview"><div className="admin-title"><div><p className="admin-kicker">BUSINESS OVERVIEW</p><h1>Good work, <em>made visible.</em></h1><p>Internal operations only. Customer accounts never receive this information.</p></div><div className="overview-actions"><div className="overview-status"><CheckCircle2 size={18}/><span>FabOS operational</span></div><div className="quick-actions"><button className="admin-ghost" onClick={()=>setModal('customer')}><Users size={15}/> Add customer</button><button className="admin-ghost" onClick={()=>setModal('production')}><Printer size={15}/> Start production</button><button className="admin-ghost" onClick={runAutomation} disabled={automating}>{automating?<RefreshCw size={15} className="spin"/>:<Activity size={15}/>} {automating?'Running…':'Automation'}</button></div></div></div>
 <section className="automation-strip"><div><p className="admin-kicker">AUTOMATION</p><strong>{d.production.automation?.enabled?'Running continuously':'Paused'}</strong><small>{d.production.automation?.auto_assign?'Auto-assigning printers & filament':'Manual resource assignment'} • {d.production.automation?.auto_start?'Auto-start enabled':'Print start requires approval'}</small></div><span>{d.production.automation?.last_run?.timestamp?'Last pass '+d.production.automation.last_run.timestamp:'Waiting for first pass'}</span></section>
 <section className="metrics"><Metric icon={ShoppingBag} label="Sales today" value={money(d.business.sales_today_cents)} sub={d.business.orders_today+' orders today'}/><Metric icon={Package} label="Active orders" value={d.business.active_orders} sub={d.business.overdue_orders+' overdue'} alert={d.business.overdue_orders>0}/><Metric icon={Printer} label="Production" value={d.production.printing_jobs+' printing'} sub={d.production.active_jobs+' active jobs'}/><Metric icon={Activity} label="Printers" value={d.printers.online+'/'+d.printers.total} sub={d.printers.total?'online':'No printers configured'}/><Metric icon={Box} label="Materials" value={d.inventory.low_filament+d.inventory.low_supplies} sub="items needing attention" alert={d.inventory.low_filament+d.inventory.low_supplies>0}/><Metric icon={Clock3} label="30-day sales" value={money(d.business.sales_30d_cents)} sub={d.business.open_quotes+' open quotes'}/></section>
 <div className="admin-grid" id="production"><section className="panel wide"><div className="panel-head"><div><p className="admin-kicker">PRODUCTION</p><h2>Jobs in motion</h2></div><span>{d.production.failed_jobs?d.production.failed_jobs+' failed':''}</span></div>{d.production.jobs.length?<div className="job-list">{d.production.jobs.map(j=><div className="job-row" key={j.id}><div className={'status-dot '+j.status}/><div className="job-main"><strong>{j.product_name}</strong><small>{j.order_number} • {j.printer_name} • {j.spool_name}</small></div><span className="job-status">{j.status}</span></div>)}</div>:<div className="empty">No active production jobs.</div>}</section>
 <section className="panel" id="quotes"><div className="panel-head"><div><p className="admin-kicker">QUOTE QUEUE</p><h2>Customer requests</h2></div><FileText size={18}/></div>{quotes.length?<div className="quote-admin-list">{quotes.slice(0,8).map(q=><div className="quote-admin-row" key={q.id}><div><strong>{q.quote_number}</strong><small>{q.customer_name||'Customer'} • {quoteStatus[String(q.status||'').toLowerCase()]||q.status}</small></div><span>{q.total_cents?money(q.total_cents):'Needs pricing'}</span><button className="quote-send proof-action" onClick={()=>openProof(q.id)}>Design proof</button>{['draft','under_review'].includes(String(q.status||'').toLowerCase())&&<button className="quote-send" onClick={()=>sendQuote(q.id)}>Approve & Send</button>}</div>)}</div>:<div className="empty">No customer quote requests.</div>}</section>
 <section className="panel"><div className="panel-head"><div><p className="admin-kicker">ACTION CENTER</p><h2>What needs attention</h2></div><AlertTriangle size={18}/></div>{d.action_items.length?<div className="action-list">{d.action_items.slice(0,8).map((a,i)=><div className={'action '+a.severity} key={a.key||i}><span>{a.title}</span><small>{a.detail}</small></div>)}</div>:<div className="empty">Nothing urgent right now.</div>}</section>
 <section className="panel" id="printers"><div className="panel-head"><div><p className="admin-kicker">PRINTER FLEET</p><h2>Machines</h2></div></div><div className="printer-list">{d.printers.items.map(p=><div className="printer-row" key={p.id}><div><strong>{p.name}</strong><small>{p.model||'3D printer'} • {p.status}</small></div><span>{p.status==='printing'?Math.round(Number(p.simulation_progress||0))+'%':'Ready'}</span></div>)}</div></section>
 <section className="panel" id="inventory"><div className="panel-head"><div><p className="admin-kicker">MATERIALS</p><h2>Low stock</h2></div></div>{d.inventory.spools.length?<div className="stock-list">{d.inventory.spools.map(s=><div className="stock-row" key={s.id}><div><strong>{s.material} {s.color||''}</strong><small>{Math.round(Number(s.remaining_g||0))}g remaining</small></div><div className="stock-bar"><i style={{width:pct(s)+'%'}}/></div></div>)}</div>:<div className="empty">All active filament is above the low-stock threshold.</div>}</section>
 <section className="panel" id="orders"><div className="panel-head"><div><p className="admin-kicker">RECENT ORDERS</p><h2>Latest business</h2></div></div><div className="orders-list">{d.recent_orders.map(o=><div className="order-row" key={o.id}><div><strong>{o.order_number}</strong><small>{o.customer_name} • {o.status}</small></div><b>{money(o.total_cents)}</b></div>)}</div></section>
 <section className="panel" id="settings"><div className="panel-head"><div><p className="admin-kicker">MAINTENANCE</p><h2>Printer service</h2></div><Settings2 size={18}/></div><div className="maintenance-list">{d.maintenance.items.map(p=><div className="maintenance-row" key={p.id}><div><strong>{p.name}</strong><small>{Number(p.hours_since_service||0).toFixed(0)}h since last service</small></div><span>{Number(p.total_hours||0).toFixed(0)}h total</span></div>)}</div></section></div></main></div></div>
 {message&&<div className="admin-toast" onClick={()=>setMessage('')}>{message}</div>}
 {modal==='customer'&&<div className="admin-modal"><div className="admin-modal-card"><button className="admin-modal-close" onClick={()=>setModal(null)}><X size={18}/></button><p className="admin-kicker">CUSTOMER</p><h2>Add a customer</h2><form onSubmit={addCustomer}><label>Name<input required value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>Email<input type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/></label><label>Phone<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>Internal notes<textarea value={customer.notes} onChange={e=>setCustomer({...customer,notes:e.target.value})}/></label><button className="admin-primary">Add customer</button></form></div></div>}
 {modal==='production'&&<div className="admin-modal"><div className="admin-modal-card"><button className="admin-modal-close" onClick={()=>setModal(null)}><X size={18}/></button><p className="admin-kicker">PRODUCTION</p><h2>Start production</h2><p className="admin-muted">Enter the order ID after payment/confirmation. FabOS will create the required production jobs and leave printer assignment to the production workflow.</p><form onSubmit={startProduction}><label>Order ID<input required value={orderId} onChange={e=>setOrderId(e.target.value)} placeholder="Order UUID"/></label><button className="admin-primary">Create production jobs</button></form></div></div>} {modal==='proof'&&<div className="admin-modal"><div className="admin-modal-card proof-admin-modal"><button className="admin-modal-close" onClick={()=>setModal(null)}><X size={18}/></button><p className="admin-kicker">DESIGN REVIEW</p><h2>Customer proof</h2><p className="admin-muted">Send the current design or upload a revised proof. A customer-approved proof is required before production can begin.</p>{proofs.length?<div className="admin-proof-history">{proofs.map(p=><div className="admin-proof-row" key={p.id}><div><strong>Version {p.design_version}</strong><small>{p.status.replace('_',' ')}{p.customer_comment?' • '+p.customer_comment:''}</small></div><span>{p.asset_name||'No file'}</span></div>)}</div>:<div className="empty">No proof versions yet.</div>}<label>Proof notes<textarea value={proofNotes} onChange={e=>setProofNotes(e.target.value)} placeholder="Explain what the customer should review."/></label><div className="proof-admin-actions"><button type="button" className="admin-ghost" onClick={sendCurrentProof} disabled={proofBusy}>{proofBusy?'Sending…':'Send current design'}</button><form onSubmit={uploadProof}><label>Upload revised proof<input type="file" accept=".stl,.3mf,.step,.stp,.obj,.png,.jpg,.jpeg" onChange={e=>setProofFile(e.target.files?.[0]||null)}/></label><button className="admin-primary" disabled={proofBusy||!proofFile}>{proofBusy?'Uploading…':'Upload & send'}</button></form></div></div></div>}</>}
function App(){const [session,setSession]=useState(()=>{try{const token=localStorage.getItem('fabos.auth.token');return token?{token}:null}catch{return null}}),[error,setError]=useState('');const logout=()=>{logoutCustomer();setSession(null)};return session?<Dashboard session={session} onLogout={logout}/>:<Login error={error} setError={setError} onLogin={setSession}/>}
createRoot(document.getElementById('root')).render(<App/>)
