import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity,AlertTriangle,Box,CheckCircle2,Clock3,LogOut,Package,Printer,RefreshCw,Settings2,ShoppingBag,Users} from 'lucide-react'
import {getOperationsDashboard,getAdminProofs,loginTeam,logoutCustomer,runOperationsAutomation} from './api.js'
import {formatCents} from './money.js'
import {getAccountType,isTeamAccountType,setAccountType,AUTH_TOKEN_KEY} from './auth.js'
import {AdminWorkspaces} from './admin-workspaces.jsx'
import './admin.css'

const pct=(r)=>(Number(r?.initial_g||0)>0?Math.max(0,Math.min(100,Number(r.remaining_g||0)/Number(r.initial_g)*100)):0)

function Login({onLogin,error,setError}){
 const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false)
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const data=await loginTeam(identifier,password);onLogin(data)}catch(err){setError(err.message||'Unable to sign in.')}finally{setBusy(false)}}
 return <main className="admin-login"><div className="admin-login-card"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><p className="admin-kicker">TEAM OPERATIONS</p><h1>Business command center.</h1><p className="admin-muted">Production, printers, orders, inventory, and business activity in one live view.</p><form onSubmit={submit}><label>Username or email<input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="admin-error">{error}</div>}<button className="admin-primary" disabled={busy}>{busy?'Signing in…':'Open FabOS Dashboard'}</button></form></div></main>
}

function Metric({icon:Icon,label,value,sub,alert}){return <div className={alert?'metric alert':'metric'}><div className="metric-icon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}

function Dashboard({session,onLogout}){
 const [activeWorkspace,setActiveWorkspace]=useState('overview')
 const [data,setData]=useState(null),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false),[automating,setAutomating]=useState(false),[proofAlerts,setProofAlerts]=useState([]),[quoteFocus,setQuoteFocus]=useState(null)
 const load=async()=>{setRefreshing(true);try{setData(await getOperationsDashboard());setError('')}catch(e){setError(e.message||'Dashboard unavailable.')}finally{setRefreshing(false)};try{setProofAlerts(await getAdminProofs({status:'changes_requested'}))}catch{setProofAlerts([])}}
 const openQuoteFromProof=quoteId=>{if(!quoteId)return;setQuoteFocus({id:quoteId,nonce:Date.now()});setActiveWorkspace('quotes')}
 const runAutomation=async()=>{setAutomating(true);try{await runOperationsAutomation();await load()}catch(e){setError(e.message||'Automation run failed.')}finally{setAutomating(false)}}
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[])
 if(error&&!data)return <div className="admin-shell"><header className="admin-header"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><button className="admin-ghost" onClick={onLogout}>Sign out</button></header><div className="admin-error-panel">{error}<button onClick={load}>Retry</button></div></div>
 const d=data||{business:{},production:{automation:{},jobs:[]},printers:{items:[],online:0,total:0},inventory:{spools:[],low_filament:0,low_supplies:0},maintenance:{items:[]},recent_orders:[],action_items:[]}
 return <div className="admin-shell"><header className="admin-header"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><div className="admin-header-right"><span className="live-dot">● LIVE</span><span>{session?.user?.name||session?.user?.email||'Team'}</span><button className="admin-icon" onClick={load} disabled={refreshing} aria-label="Refresh"><RefreshCw size={17} className={refreshing?'spin':''}/></button><button className="admin-ghost" onClick={onLogout}><LogOut size={15}/> Sign out</button></div></header>
 <main className="admin-main"><div className="admin-title"><div><p className="admin-kicker">BUSINESS OVERVIEW</p><h1>Good work, <em>made visible.</em></h1><p>Live operating picture for FABVEX. Updated every 5 seconds.</p></div><div className="overview-actions"><div className="overview-status"><CheckCircle2 size={18}/><span>FabOS operational</span></div><button className="admin-ghost" onClick={runAutomation} disabled={automating}>{automating?<RefreshCw size={15} className="spin"/>:<Activity size={15}/>} {automating?"Running…":"Run automation now"}</button></div></div>
 <div className="workspace-nav" aria-label="FabOS workspaces"><button className={activeWorkspace==='overview'?'active':''} onClick={()=>setActiveWorkspace('overview')}>Overview</button><button className={activeWorkspace==='operations'?'active':''} onClick={()=>setActiveWorkspace('operations')}>Operations</button><button className={activeWorkspace==='inventory'?'active':''} onClick={()=>setActiveWorkspace('inventory')}>Inventory</button><button className={activeWorkspace==='designs'?'active':''} onClick={()=>setActiveWorkspace('designs')}>Design Vault</button><button className={activeWorkspace==='qc'?'active':''} onClick={()=>setActiveWorkspace('qc')}>QC</button><button className={activeWorkspace==='catalog'?'active':''} onClick={()=>setActiveWorkspace('catalog')}>Catalog</button><button className={activeWorkspace==='customers'?'active':''} onClick={()=>setActiveWorkspace('customers')}>Customers</button><button className={activeWorkspace==='quotes'?'active':''} onClick={()=>setActiveWorkspace('quotes')}>Quotes</button><button className={activeWorkspace==='proofs'?'active':''} onClick={()=>setActiveWorkspace('proofs')}>Proofs</button><button className={activeWorkspace==='marketing'?'active':''} onClick={()=>setActiveWorkspace('marketing')}>Marketing</button><button className={activeWorkspace==='invoices'?'active':''} onClick={()=>setActiveWorkspace('invoices')}>Billing</button><button className={activeWorkspace==='fulfillment'?'active':''} onClick={()=>setActiveWorkspace('fulfillment')}>Fulfillment</button><button className={activeWorkspace==='health'?'active':''} onClick={()=>setActiveWorkspace('health')}>Health</button><button className={activeWorkspace==='ai'?'active':''} onClick={()=>setActiveWorkspace('ai')}>AI</button><button className={activeWorkspace==='users'?'active':''} onClick={()=>setActiveWorkspace('users')}>Team</button><button className={activeWorkspace==='settings'?'active':''} onClick={()=>setActiveWorkspace('settings')}>Settings</button></div>
 <section className="automation-strip"><div><p className="admin-kicker">AUTOMATION</p><strong>{d.production.automation?.enabled?"Running continuously":"Paused"}</strong><small>{d.production.automation?.auto_assign?"Auto-assigning printers & filament":"Manual resource assignment"} • {d.production.automation?.auto_start?"Auto-start enabled":"Print start requires approval"}</small></div><span>{d.production.automation?.last_run?.timestamp?"Last pass "+d.production.automation.last_run.timestamp:"Waiting for first pass"}</span></section>\n <section className="metrics"><Metric icon={ShoppingBag} label="Sales today" value={formatCents(d.business.sales_today_cents)} sub={d.business.orders_today+' orders today'}/><Metric icon={Package} label="Active orders" value={d.business.active_orders} sub={d.business.overdue_orders+' overdue'} alert={d.business.overdue_orders>0}/><Metric icon={Printer} label="Production" value={d.production.printing_jobs+' printing'} sub={d.production.active_jobs+' active jobs'}/><Metric icon={Activity} label="Printers" value={d.printers.online+'/'+d.printers.total} sub={d.printers.total?'online':'No printers configured'}/><Metric icon={Box} label="Materials" value={d.inventory.low_filament+d.inventory.low_supplies} sub="items needing attention" alert={d.inventory.low_filament+d.inventory.low_supplies>0}/><Metric icon={Clock3} label="30-day sales" value={formatCents(d.business.sales_30d_cents)} sub={d.business.open_quotes+' open quotes'}/></section>
 <div className="admin-grid"><section className="panel wide"><div className="panel-head"><div><p className="admin-kicker">PRODUCTION</p><h2>Jobs in motion</h2></div><span>{d.production.failed_jobs?d.production.failed_jobs+' failed':''}</span></div>{d.production.jobs.length?<div className="job-list">{d.production.jobs.map(j=><div className="job-row" key={j.id}><div className={'status-dot '+j.status}/><div className="job-main"><strong>{j.product_name}</strong><small>{j.order_number} • {j.printer_name} • {j.spool_name}</small></div><span className="job-status">{j.status}</span></div>)}</div>:<div className="empty">No active production jobs.</div>}</section>
 <section className="panel"><div className="panel-head"><div><p className="admin-kicker">ACTION CENTER</p><h2>What needs attention</h2></div><AlertTriangle size={18}/></div>{(proofAlerts.length||d.action_items.length)?<div className="action-list">{proofAlerts.map(p=>{const comment=String(p.customer_comment||'').trim();return <button className="action high" key={p.id} onClick={()=>openQuoteFromProof(p.quote_id)}><span>Proof changes requested — {p.quote_number||'quote'}</span><small>{comment?('“'+(comment.length>110?comment.slice(0,109)+'…':comment)+'” · '):''}{p.design_name||'Design proof'} · open the quote to reply</small></button>})}{d.action_items.slice(0,8).map((a,i)=><div className={'action '+a.severity} key={a.key||i}><span>{a.title}</span><small>{a.detail}</small></div>)}</div>:<div className="empty">Nothing urgent right now.</div>}</section>
 <section className="panel"><div className="panel-head"><div><p className="admin-kicker">PRINTER FLEET</p><h2>Machines</h2></div></div><div className="printer-list">{d.printers.items.map(p=><div className="printer-row" key={p.id}><div><strong>{p.name}</strong><small>{p.model||'3D printer'} • {p.status}</small></div><span>{p.status==='printing'?Math.round(Number(p.simulation_progress||0))+'%':'Ready'}</span></div>)}</div></section>
 <section className="panel"><div className="panel-head"><div><p className="admin-kicker">MATERIALS</p><h2>Low stock</h2></div></div>{d.inventory.spools.length?<div className="stock-list">{d.inventory.spools.map(s=><div className="stock-row" key={s.id}><div><strong>{s.material} {s.color||''}</strong><small>{Math.round(Number(s.remaining_g||0))}g remaining</small></div><div className="stock-bar"><i style={{width:pct(s)+'%'}}/></div></div>)}</div>:<div className="empty">All active filament is above the low-stock threshold.</div>}</section>
 <section className="panel"><div className="panel-head"><div><p className="admin-kicker">RECENT ORDERS</p><h2>Latest business</h2></div></div><div className="orders-list">{d.recent_orders.map(o=><div className="order-row" key={o.id}><div><strong>{o.order_number}</strong><small>{o.customer_name} • {o.status}</small></div><b>{formatCents(o.total_cents)}</b></div>)}</div></section>
 <section className="panel"><div className="panel-head"><div><p className="admin-kicker">MAINTENANCE</p><h2>Printer service</h2></div><Settings2 size={18}/></div><div className="maintenance-list">{d.maintenance.items.map(p=><div className="maintenance-row" key={p.id}><div><strong>{p.name}</strong><small>{Number(p.hours_since_service||0).toFixed(0)}h since last service</small></div><span>{Number(p.total_hours||0).toFixed(0)}h total</span></div>)}</div></section><section className="panel wide"><div className="panel-head"><div><p className="admin-kicker">AI CAD</p><h2>Generated designs</h2></div><span>{d.cad?.total||0} total{d.cad?.failed?` · ${d.cad.failed} failed`:``}</span></div>{d.cad?.recent_jobs?.length?<div className="job-list">{d.cad.recent_jobs.map(job=><div className="job-row" key={job.id}><div className={"status-dot "+String(job.status||"")}/><div className="job-main"><strong>{job.spec?.shape?String(job.spec.shape).replace(/_/g," "):"CAD design"}</strong><small>{job.prompt||"Parametric CAD job"}{job.verification?.passed===true?" • verified":job.verification?.passed===false?" • verification failed":""}</small></div><span className="job-status">{job.status}</span></div>)}</div>:<div className="empty">No generated CAD jobs yet.</div>}</section></div>{activeWorkspace!=='overview'&&<AdminWorkspaces active={activeWorkspace} dashboard={d} onRefresh={load} busy={refreshing} onOpenQuote={openQuoteFromProof} quoteFocus={quoteFocus}/>}</main></div>
}

function AccessDenied({onLogout}){
 return <main className="admin-login"><div className="admin-login-card"><div className="admin-brand"><img src="/brand/fabvex-mark.svg" alt=""/><span>FABVEX <b>FABOS</b></span></div><p className="admin-kicker">TEAM OPERATIONS</p><h1>Team access only.</h1><p className="admin-muted">This console is for Fabvex team accounts. The signed-in account doesn't have team access, so the dashboard wasn't loaded.</p><div className="admin-denied-actions"><a className="admin-primary" href="/account.html">Go to my account</a> <button className="admin-ghost" onClick={onLogout}>Sign out</button></div></div></main>
}

function restoreSession(){
 try{
  const token=localStorage.getItem(AUTH_TOKEN_KEY)
  if(!token)return null
  return {token,accountType:getAccountType()}
 }catch{return null}
}

function App(){
 const [session,setSession]=useState(restoreSession)
 const [error,setError]=useState('')
 const [status,setStatus]=useState(()=>{const s=restoreSession();if(!s)return 'login';if(isTeamAccountType(s.accountType))return 'ok';return s.accountType?'denied':'verify'})
 const logout=()=>{logoutCustomer();setSession(null);setStatus('login')}
 const handleLogin=data=>{const accountType=String(data?.user?.account_type||'').toLowerCase();setSession({token:data?.token||'',accountType,user:data?.user});setStatus('ok')}
 const retry=()=>{setError('');setStatus('verify')}
 useEffect(()=>{
  if(status!=='verify'||!session)return
  let cancelled=false
  getOperationsDashboard()
   .then(data=>{if(cancelled)return;const accountType=String(data?.viewer?.account_type||'').toLowerCase();if(accountType)setAccountType(accountType);setSession(s=>({...s,accountType:accountType||s?.accountType}));setStatus('ok')})
   .catch(err=>{if(cancelled)return;if(/\b(401|403)\b|forbidden|denied/i.test(String(err?.message||'')))setStatus('denied');else{setError(err?.message||'Could not verify this session.');setStatus('verify-error')}})
  return()=>{cancelled=true}
 },[status,session])
 if(status==='login')return <Login error={error} setError={setError} onLogin={handleLogin}/>
 if(status==='verify')return <main className="admin-login"><div className="admin-login-card"><p className="admin-kicker">TEAM OPERATIONS</p><h1>Verifying session…</h1><p className="admin-muted">Checking this sign-in against the team console.</p></div></main>
 if(status==='verify-error')return <main className="admin-login"><div className="admin-login-card"><p className="admin-kicker">TEAM OPERATIONS</p><h1>Session check failed.</h1><p className="admin-muted">{error}</p><button className="admin-primary" onClick={retry}>Retry</button> <button className="admin-ghost" onClick={logout}>Sign out</button></div></main>
 if(status==='denied')return <AccessDenied onLogout={logout}/>
 return <Dashboard session={session} onLogout={logout}/>
}
createRoot(document.getElementById('root')).render(<App/>)
