import React,{useState} from 'react'
import {ArrowLeft,ArrowRight,Box,Check,Minus,Plus,ShoppingCart} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {readCart,writeCart,cartCount,cartSubtotal,changeCartItem} from './cart.js'
import {createOrderNumber,saveOrder} from './order-store.js'
import {buildOrderPayload} from './customer-contracts.js'
import './styles.css'

function App(){
 const [cart,setCart]=useState(readCart)
 const [submitted,setSubmitted]=useState(null)
 const [form,setForm]=useState({name:'',email:'',address:'',city:'',state:'',zip:'',notes:''})
 const count=cartCount(cart),subtotal=cartSubtotal(cart),shipping=subtotal>75?0:8,total=subtotal+shipping
 const updateCart=(next)=>{setCart(next);writeCart(next)}
 const update=(key,value)=>setForm(v=>({...v,[key]:value}))
 const submit=e=>{e.preventDefault();if(!cart.length)return;const payload=buildOrderPayload({cart,form,subtotal,shipping,total});const order={orderNumber:createOrderNumber(),createdAt:new Date().toISOString(),status:'Order received',customer:payload.customer,shippingAddress:payload.shippingAddress,notes:payload.notes,items:cart.map(item=>({...item})),subtotal,shipping,total,contractVersion:payload.contractVersion,channel:payload.channel,payload};saveOrder(order);setSubmitted(order);writeCart([]);setCart([])}
 if(submitted)return <div className="checkout-shell"><header className="checkout-nav"><a href="/" className="checkout-brand"><Box size={18}/> FAB<span>OS</span></a></header><main className="checkout-success"><div className="success-mark"><Check size={34}/></div><p className="eyebrow">ORDER RECEIVED</p><h1>You're all set.</h1><p>Your order has been recorded and is ready for the next step. No payment was processed in this prototype.</p><div className="checkout-order-reference"><span>ORDER NUMBER</span><strong>{submitted.orderNumber}</strong><small>{submitted.items.length} {submitted.items.length===1?'item':'items'} · ${submitted.total.toFixed(2)} total</small></div><div className="checkout-success-actions"><a className="button primary" href="/orders.html">View your orders <ArrowRight size={17}/></a><a className="button secondary" href="/shop.html">Continue shopping</a></div></main></div>
 return <div className="checkout-shell"><header className="checkout-nav"><a href="/" className="checkout-brand"><Box size={18}/> FAB<span>OS</span></a><div className="checkout-nav-links"><a href="/orders.html">My orders</a><span className="checkout-secure">CHECKOUT</span></div></header><main className="checkout-main"><a className="back-link" href="/shop.html"><ArrowLeft size={16}/> Continue shopping</a><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><p className="eyebrow">CUSTOMER DETAILS</p><h1>Complete your order.</h1><p className="checkout-intro">Tell us where to send it. Payment will be added when the customer checkout service is connected.</p><section><h2>Contact</h2><div className="field-grid"><label>Full name<input required value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Email<input required type="email" value={form.email} onChange={e=>update('email',e.target.value)}/></label></div></section><section><h2>Shipping address</h2><label>Street address<input required value={form.address} onChange={e=>update('address',e.target.value)}/></label><div className="field-grid three"><label>City<input required value={form.city} onChange={e=>update('city',e.target.value)}/></label><label>State<input required value={form.state} onChange={e=>update('state',e.target.value)}/></label><label>ZIP code<input required value={form.zip} onChange={e=>update('zip',e.target.value)}/></label></div></section><section><h2>Order notes <span>Optional</span></h2><textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Anything we should know about your order?"/></section><button className="button primary checkout-submit" disabled={!cart.length}>Place order <ArrowRight size={17}/></button><p className="checkout-disclaimer">No payment is processed in this prototype.</p></form><aside className="order-summary"><div className="summary-head"><div><p className="eyebrow">YOUR ORDER</p><h2>{count} {count===1?'item':'items'}</h2></div><ShoppingCart size={20}/></div>{cart.length?<><div className="summary-items">{cart.map(item=><div className="summary-item" key={item.id}><div><strong>{item.name}</strong><small>${item.price} each</small></div><div className="summary-qty"><button type="button" onClick={()=>updateCart(changeCartItem(cart,item.id,-1))}><Minus size={13}/></button><span>{item.quantity}</span><button type="button" onClick={()=>updateCart(changeCartItem(cart,item.id,1))}><Plus size={13}/></button></div></div>)}</div><div className="summary-lines"><div><span>Subtotal</span><strong>${subtotal}</strong></div><div><span>Shipping</span><strong>{shipping?'$'+shipping:'Free'}</strong></div><div className="summary-total"><span>Total</span><strong>${total}</strong></div></div></>:<div className="summary-empty"><ShoppingCart size={28}/><p>Your cart is empty.</p><a href="/shop.html">Browse projects</a></div>}</aside></div></main></div>
}
createRoot(document.getElementById('checkout-root')).render(<App/>)
