import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowLeft, ArrowRight, Box, Check, Upload, X } from 'lucide-react'

const initial={idea:'',dimensions:'',material:'',quantity:'1',name:'',email:'',notes:''}

function App(){
 const [step,setStep]=useState(1)
 const [data,setData]=useState(initial)
 const [file,setFile]=useState(null)
 const [submitted,setSubmitted]=useState(false)
 const update=(key,value)=>setData(d=>({...d,[key]:value}))
 const next=()=>setStep(s=>Math.min(4,s+1))
 const back=()=>setStep(s=>Math.max(1,s-1))
 const submit=e=>{e.preventDefault();setSubmitted(true)}
 if(submitted)return <main className="cw-shell"><header className="cw-nav"><a className="cw-brand" href="/"><span className="cw-mark"><Box size={18}/></span>FAB<span>OS</span></a><a className="cw-back" href="/">Back to FabOS</a></header><section className="cw-success"><div className="cw-success-mark"><Check size={34}/></div><p className="cw-eyebrow">REQUEST RECEIVED</p><h1>Let's see what<br/><em>we can build.</em></h1><p>Your project details are ready for review. In the connected version, this request will flow directly into the quoting system.</p><div className="cw-reference"><span>PROJECT</span><strong>{data.idea}</strong>{file&&<small>File: {file.name}</small>}</div><a className="cw-button cw-dark" href="/">Return to home <ArrowRight size={17}/></a></section></main>
 return <main className="cw-shell"><header className="cw-nav"><a className="cw-brand" href="/"><span className="cw-mark"><Box size={18}/></span>FAB<span>OS</span></a><a className="cw-back" href="/">Exit request <X size={15}/></a></header><section className="cw-layout"><aside className="cw-intro"><p className="cw-eyebrow">CUSTOM WORK</p><h1>Make something<br/><em>that doesn't exist.</em></h1><p>Give us the idea, the important details, and a way to reach you. We'll use that information to figure out the right way to make it.</p><div className="cw-promise"><span>01</span><div><strong>Tell us the problem</strong><small>Start with what you need the part to do.</small></div></div><div className="cw-promise"><span>02</span><div><strong>Give us the details</strong><small>Dimensions, material preferences, and files help.</small></div></div><div className="cw-promise"><span>03</span><div><strong>Review the request</strong><small>We'll have a clear starting point for a quote.</small></div></div></aside><section className="cw-card"><div className="cw-progress">{['Idea','Details','Contact','Review'].map((label,i)=><div className={step===i+1?'active':step>i+1?'done':''} key={label}><span>{String(i+1).padStart(2,'0')}</span>{label}</div>)}</div><form onSubmit={submit}>
 {step===1&&<div className="cw-step"><p className="cw-kicker">01 · THE IDEA</p><h2>What are you trying to make?</h2><p className="cw-help">Describe the part, project, or problem. You don't need to know exactly how it should be designed.</p><textarea autoFocus value={data.idea} onChange={e=>update('idea',e.target.value)} placeholder="Example: I need a wall mount for a small device, but the existing mount doesn't fit my space." required/><div className="cw-actions"><button type="button" className="cw-button cw-dark" disabled={!data.idea.trim()} onClick={next}>Continue <ArrowRight size={17}/></button></div></div>}
 {step===2&&<div className="cw-step"><p className="cw-kicker">02 · THE DETAILS</p><h2>Help us understand the part.</h2><p className="cw-help">Approximate information is fine. If you're unsure, say so—we can work from there.</p><div className="cw-grid"><label>Approximate dimensions<input value={data.dimensions} onChange={e=>update('dimensions',e.target.value)} placeholder="120 × 80 × 35 mm"/></label><label>Quantity<input type="number" min="1" value={data.quantity} onChange={e=>update('quantity',e.target.value)}/></label></div><label>Preferred material<input value={data.material} onChange={e=>update('material',e.target.value)} placeholder="PETG, PLA, flexible, unsure..."/></label><label>Model or reference file<div className="cw-upload"><Upload size={24}/><strong>{file?file.name:'Drop a file here or browse'}</strong><small>STL · 3MF · OBJ · STEP · JPG · PNG</small><input type="file" accept=".stl,.3mf,.obj,.step,.stp,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></div></label><div className="cw-actions"><button type="button" className="cw-button cw-light" onClick={back}><ArrowLeft size={16}/> Back</button><button type="button" className="cw-button cw-dark" onClick={next}>Continue <ArrowRight size={17}/></button></div></div>}
 {step===3&&<div className="cw-step"><p className="cw-kicker">03 · CONTACT</p><h2>Where should we send the quote?</h2><p className="cw-help">We'll use this only to follow up about your custom project.</p><div className="cw-grid"><label>Name<input autoFocus value={data.name} onChange={e=>update('name',e.target.value)} placeholder="Your name" required/></label><label>Email<input type="email" value={data.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com" required/></label></div><label>Anything else we should know?<textarea className="cw-notes" value={data.notes} onChange={e=>update('notes',e.target.value)} placeholder="Deadline, how the part will be used, special requirements, etc."/></label><div className="cw-actions"><button type="button" className="cw-button cw-light" onClick={back}><ArrowLeft size={16}/> Back</button><button type="button" className="cw-button cw-dark" disabled={!data.name.trim()||!data.email.trim()} onClick={next}>Review request <ArrowRight size={17}/></button></div></div>}
 {step===4&&<div className="cw-step"><p className="cw-kicker">04 · REVIEW</p><h2>Make sure we've got it.</h2><p className="cw-help">This is the information we'll use as the starting point for your quote.</p><div className="cw-review"><div><span>PROJECT</span><strong>{data.idea}</strong></div><div><span>DETAILS</span><strong>{data.dimensions||'Not specified'} · {data.quantity} piece{data.quantity==='1'?'':'s'}</strong><strong>{data.material||'Material to be determined'}</strong></div><div><span>CONTACT</span><strong>{data.name}</strong><strong>{data.email}</strong></div>{file&&<div><span>FILE</span><strong>{file.name}</strong></div>}{data.notes&&<div><span>NOTES</span><strong>{data.notes}</strong></div>}</div><div className="cw-actions"><button type="button" className="cw-button cw-light" onClick={back}><ArrowLeft size={16}/> Back</button><button className="cw-button cw-accent">Submit quote request <ArrowRight size={17}/></button></div></div>}
 </form></section></section></main>
}
createRoot(document.getElementById('custom-root')).render(<App />)
