import React,{useEffect,useState} from 'react'
import {ArrowRight,Box,Check,LogIn,Menu,ShoppingCart,Sun,Moon,X} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {readCart,cartCount} from './cart.js'
import {getPublicCatalog,catalogImageUrl} from './api.js'
import {getTheme,setTheme} from './theme.js'
import './styles.css'
import './home-redesign.css'
function Header(){const [open,setOpen]=useState(false),[theme,setThemeState]=useState(getTheme());const count=cartCount(readCart());const toggleTheme=()=>{const next=theme==='dark'?'light':'dark';setTheme(next);setThemeState(next)};return <header className="nv2"><a className="brand nv2-brand" href="/"><span className="brand-mark"><img src="/brand/fabvex-mark.svg" alt="" /></span><span>FAB<span>VEX</span></span></a><nav className={open?'nv2-links open':'nv2-links'}><a href="#services" onClick={()=>setOpen(false)}>Services</a><a href="/shop.html" onClick={()=>setOpen(false)}>Catalog</a><a href="/custom-work.html" onClick={()=>setOpen(false)}>Custom Work</a><a href="#process" onClick={()=>setOpen(false)}>How It Works</a><a href="/about.html" onClick={()=>setOpen(false)}>About</a></nav><div className="nv2-actions"><a className="nv2-login" href="/account.html"><LogIn size={16}/> Log In</a><button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle dark and light mode">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><a className="nv2-cart" href="/checkout.html" aria-label={'Shopping cart, '+count+' items'}><ShoppingCart size={18}/>{count>0&&<span>{count}</span>}</a><button className="nv2-menu" onClick={()=>setOpen(v=>!v)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></header>}
function Capability({icon:Icon,title,copy}){return <div className="capability"><span className="cap-icon"><Icon size={18}/></span><div><strong>{title}</strong><small>{copy}</small></div></div>}
function App(){const [products,setProducts]=useState([]);useEffect(()=>{getPublicCatalog().then(items=>setProducts(items.slice(0,4))).catch(()=>{})},[]);return <div className="nv2-shell"><Header/><main>
<section className="nv2-hero"><div className="nv2-hero-copy"><p className="nv2-eyebrow">CUSTOM 3D PRINTING · FABVEX</p><h1>Ideas in.<br/><em>Real parts out.</em></h1><p className="nv2-lead">From a quick replacement part to a completely original product, FABVEX turns digital ideas into useful, physical things.</p><div className="nv2-hero-actions"><a className="nv2-button nv2-primary" href="/custom-work.html">Start a Project <ArrowRight size={17}/></a><a className="nv2-button nv2-secondary" href="/shop.html">Explore the Catalog</a></div><div className="nv2-proof"><span><Check size={14}/> Made to order</span><span><Check size={14}/> Quality checked</span><span><Check size={14}/> Customer-owned designs welcome</span></div></div><div className="nv2-hero-visual"><div className="nv2-gridline grid-a"/><div className="nv2-gridline grid-b"/><div className="nv2-orbit orbit-a"/><div className="nv2-orbit orbit-b"/><div className="nv2-part"><Box size={126}/><span>FABVEX<br/><b>PRECISION PRINT</b></span></div><div className="nv2-readout"><small>LIVE PROCESS</small><strong>BUILD / 03</strong><i/></div></div></section>
<section className="nv2-capability-strip"><Capability icon={Box} title="Custom Parts" copy="Built around your need"/><Capability icon={Check} title="Prototypes" copy="Test before you commit"/><Capability icon={ShoppingCart} title="Ready to Print" copy="Shop proven designs"/><Capability icon={ArrowRight} title="Small Batches" copy="From one to production runs"/><Capability icon={LogIn} title="Customer Portal" copy="Quotes, files & orders"/></section>
<section className="nv2-paths"><div className="nv2-section-head"><p className="nv2-eyebrow">CHOOSE YOUR STARTING POINT</p><h2>One business.<br/><em>Three ways in.</em></h2></div><div className="nv2-path-grid"><a className="nv2-path path-green" href="/shop.html"><span>01</span><h3>Buy a finished design</h3><p>Browse ready-to-print products, configure the available options, and place your order.</p><b>Browse catalog <ArrowRight size={16}/></b></a><a className="nv2-path path-blue" href="/custom-work.html"><span>02</span><h3>Make something custom</h3><p>Bring a file, drawing, photo, dimensions, or simply describe the problem you need solved.</p><b>Start custom work <ArrowRight size={16}/></b></a><a className="nv2-path path-red" href="/custom-work.html"><span>03</span><h3>Develop a real product</h3><p>Prototype, revise, verify the design, then move from one-off parts into small production runs.</p><b>Talk through a project <ArrowRight size={16}/></b></a></div></section>
<section className="nv2-services" id="services"><div className="nv2-section-head wide"><p className="nv2-eyebrow">WHAT FABVEX DOES</p><h2>More than <em>printing.</em></h2><p>The printer is the tool. The real service is helping you get from an idea to a part that actually works.</p></div><div className="nv2-service-layout"><div className="nv2-service-feature"><div className="service-number">01</div><Box size={42}/><h3>Functional & End-Use Parts</h3><p>Brackets, mounts, enclosures, replacement parts, organizers, fixtures, and other useful components designed for the job they're meant to do.</p><a href="/custom-work.html">Build a functional part <ArrowRight size={16}/></a></div><div className="nv2-service-list"><div><span>02</span><div><h3>Prototypes & Product Design</h3><p>Iterate on an idea before spending on a larger production run.</p></div></div><div><span>03</span><div><h3>Custom Orders & Small Batches</h3><p>One piece is fine. A repeatable run is fine too.</p></div></div><div><span>04</span><div><h3>Design Support & File Prep</h3><p>Already have a model? Need help getting one ready? Start with what you have.</p></div></div><div><span>05</span><div><h3>Material & Finish Choices</h3><p>Choose based on appearance, flexibility, strength, temperature, and use.</p></div></div></div></div></section>
<section className="nv2-catalog-preview"><div className="nv2-section-head"><p className="nv2-eyebrow">READY TO PRINT</p><h2>Useful things,<br/><em>already figured out.</em></h2><p>Start with a proven design or use it as inspiration for something custom.</p></div>{products.length?<div className="nv2-product-row">{products.map(p=><a className="nv2-product" href={'/product.html?id='+encodeURIComponent(p.id)} key={p.id}><div>{p.images?.length?<img src={catalogImageUrl(p.images.find(i=>i.is_primary)||p.images[0])} alt={p.name}/>:<Box size={54}/>}</div><section><strong>{p.name}</strong><small>{p.category||'Custom 3D Print'}</small><b>{'$'+Number(p.price||0).toFixed(2)} <ArrowRight size={14}/></b></section></a>)}</div>:<div className="nv2-empty">Catalog products will appear here when published.</div>}<a className="nv2-outline-link" href="/shop.html">View the complete catalog <ArrowRight size={16}/></a></section>
<section className="nv2-process" id="process"><div className="nv2-section-head"><p className="nv2-eyebrow">THE FABVEX WORKFLOW</p><h2>Simple for you.<br/><em>Controlled by us.</em></h2></div><div className="nv2-process-line">{[['01','Tell us what you need','Submit a file, idea, dimensions, or custom request.'],['02','We review the job','Your request is reviewed before a final quote is approved.'],['03','You approve the result','For custom designs, you can review proofs before production.'],['04','We make & deliver','Production, quality check, and fulfillment happen from the same workflow.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="nv2-custom-cta"><div><p className="nv2-eyebrow">HAVE SOMETHING IN MIND?</p><h2>Bring the rough idea.<br/><em>We'll figure out the rest.</em></h2><p>You don't need a perfect CAD file to start. FabOS gives you a place to submit the project, files, dimensions, and notes so the job can be reviewed before anything is printed.</p><a className="nv2-button nv2-primary" href="/custom-work.html">Start a Custom Project <ArrowRight size={17}/></a></div><div className="nv2-cta-visual"><div/><div/><div/></div></section>
</main><footer className="nv2-footer"><div className="brand"><span className="brand-mark"><img src="/brand/fabvex-mark.svg" alt=""/></span><span>FAB<span>VEX</span></span></div><div><a href="/account.html">Customer Login</a><a href="/shop.html">Catalog</a><a href="/custom-work.html">Custom Work</a></div><small>© 2026 FABVEX. Built for real-world ideas.</small></footer></div>}
createRoot(document.getElementById('root')).render(<App/>)
