import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, Box, Check, Menu, Minus, Plus, ShoppingCart, Sparkles, X } from 'lucide-react'
import './styles.css'

const products = [
  { id:'dock', name:'Desk Cable Dock', price:18, tag:'Best Seller', category:'Desk & Office', description:'A clean, compact home for the cables that never stay put.' },
  { id:'stand', name:'Controller Stand', price:24, tag:'Popular', category:'Gaming', description:'Weighted, low-profile support built for everyday use.' },
  { id:'hook', name:'Headphone Hook', price:16, tag:'New', category:'Desk & Office', description:'A simple under-desk mount that keeps your setup clear.' },
  { id:'organizer', name:'Modular Home Organizer', price:32, tag:'Popular', category:'Home', description:'Stackable storage designed around the things you actually own.' },
  { id:'mount', name:'Utility Mount', price:21, tag:'Made to Order', category:'Home', description:'A compact mounting solution for awkward spaces.' },
  { id:'gaming', name:'Gaming Desk Dock', price:29, tag:'New', category:'Gaming', description:'Keep controllers, cables, and accessories within reach.' },
]
const categories=['All','Desk & Office','Gaming','Home']
const faqs=[
 ['How long does an order take?','Most standard projects are produced in a few business days. Custom projects can vary based on complexity.'],
 ['Can you print a design I already have?','Absolutely. Upload your model during the custom project process and we can review it before production.'],
 ['What materials and colors are available?','We can offer a growing range of common 3D-printing materials, finishes, and colors depending on the project.']
]

function App(){
 const [menuOpen,setMenuOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[cart,setCart]=useState([]),[category,setCategory]=useState('All'),[openFaq,setOpenFaq]=useState(0)
 const visible=useMemo(()=>category==='All'?products:products.filter(p=>p.category===category),[category])
 const count=cart.reduce((n,i)=>n+i.quantity,0), subtotal=cart.reduce((n,i)=>n+i.price*i.quantity,0)
 const add=p=>{setCart(items=>items.some(i=>i.id===p.id)?items.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...items,{...p,quantity:1}]);setCartOpen(true)}
 const change=(id,d)=>setCart(items=>items.flatMap(i=>i.id!==id?[i]:i.quantity+d>0?[{...i,quantity:i.quantity+d}]:[]))
 return <div className="site-shell">
  <header className="nav"><a className="brand" href="#top"><span className="brand-mark"><Box size={18}/></span><span>FAB<span>OS</span></span></a><nav className={menuOpen?'nav-links open':'nav-links'}><a href="#shop" onClick={()=>setMenuOpen(false)}>Shop</a><a href="#custom" onClick={()=>setMenuOpen(false)}>Custom Work</a><a href="#process" onClick={()=>setMenuOpen(false)}>How It Works</a><a href="#about" onClick={()=>setMenuOpen(false)}>About</a></nav><div className="nav-actions"><button className="cart" onClick={()=>setCartOpen(true)} aria-label={`Shopping cart, ${count} items`}><ShoppingCart size={19}/>{count>0&&<span>{count}</span>}</button><button className="menu-button" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle menu">{menuOpen?<X/>:<Menu/>}</button></div></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> BUILT FOR REAL LIFE</p><h1>3D printed.<br/><em>Engineered</em> for you.</h1><p className="hero-text">Useful things, custom solutions, and one-off ideas brought to life with precision 3D printing.</p><div className="hero-buttons"><a className="button primary" href="#shop">Shop Projects <ArrowRight size={17}/></a><a className="button secondary" href="#custom">Need something custom?</a></div><div className="trust-row"><span><Check size={15}/> Made to order</span><span><Check size={15}/> Quality checked</span><span><Check size={15}/> Ships with care</span></div></div><div className="hero-object"><div className="object-ring ring-one"/><div className="object-ring ring-two"/><div className="floating-cube"><Box size={76}/></div><div className="object-label">PRECISION<br/><strong>MADE</strong></div></div></section>
   <section className="process" id="process"><div className="section-heading centered"><p className="eyebrow">HOW IT WORKS</p><h2>From idea to <em>finished part.</em></h2></div><div className="steps">{[['01','Choose or create','Pick a ready-to-print project or tell us what you need.'],['02','We make it real','We prepare, print, inspect, and finish your part.'],['03','It shows up','Your finished piece is packed carefully and shipped to you.']].map(([n,t,d])=><div className="step" key={n}><div className="step-number">{n}</div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
   <section className="shop-section" id="shop"><div className="section-heading"><p className="eyebrow">POPULAR PROJECTS</p><h2>Things worth <em>printing.</em></h2><p>Start with something useful. Everything here is designed to be practical, durable, and good-looking.</p></div><div className="category-row">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><div className="product-image"><div className="product-shape"><Box size={58}/></div><span>{p.tag}</span></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.description}</p></div><strong>${p.price}</strong></div><button className="add-button" onClick={()=>add(p)}>Add to cart <Plus size={16}/></button></article>)}</div></section>
   <section className="custom" id="custom"><div className="custom-panel"><div className="custom-copy"><p className="eyebrow">CUSTOM WORK</p><h2>Have an idea?<br/><em>Let's build it.</em></h2><p>From a replacement part to a completely original creation, custom printing is where we get to make something that doesn't exist yet.</p><a className="button light" href="#contact">Start a custom project <ArrowRight size={17}/></a></div><div className="custom-examples"><div className="example-main"><Box size={100}/><small>CUSTOM PANEL</small></div><div className="example-side"><div><Box size={30}/><span>Mounts</span></div><div><Box size={30}/><span>Enclosures</span></div><div><Box size={30}/><span>Brackets</span></div></div></div></div></section>
   <section className="about" id="about"><div><p className="eyebrow">WHY FABOS</p><h2>Not just a printer.<br/><em>A better way to make.</em></h2></div><div className="about-copy"><p>Good 3D printing isn't about pressing a button and hoping for the best. It's about choosing the right process, material, geometry, and finish for what the part actually needs to do.</p><p>That's the difference we bring to every order — whether it's a small desk accessory or a completely custom build.</p></div></section>
   <section className="faq" id="contact"><div className="section-heading centered"><p className="eyebrow">QUESTIONS</p><h2>Before you <em>order.</em></h2></div>{faqs.map(([q,a],i)=><div className="faq-row" key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span>{openFaq===i?<Minus size={18}/>:<Plus size={18}/>}</button>{openFaq===i&&<p>{a}</p>}</div>)}</section>
  </main>
  <footer><div className="brand"><span className="brand-mark"><Box size={17}/></span><span>FAB<span>OS</span></span></div><p>Useful things. Made better.</p><small>© 2026 FabOS. All rights reserved.</small></footer>
  {cartOpen&&<div className="cart-overlay" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="cart-head"><div><p className="eyebrow">YOUR CART</p><h2>{count} {count===1?'item':'items'}</h2></div><button onClick={()=>setCartOpen(false)} aria-label="Close cart"><X/></button></div>{cart.length===0?<div className="cart-empty"><ShoppingCart size={36}/><h3>Your cart is empty.</h3><p>Find something useful and add it here.</p><button className="button primary" onClick={()=>{setCartOpen(false);document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'})}}>Browse projects <ArrowRight size={16}/></button></div>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><div className="mini-product"><Box size={28}/></div><div className="cart-item-main"><strong>{i.name}</strong><span>${i.price} each</span><div className="quantity"><button onClick={()=>change(i.id,-1)}><Minus size={13}/></button><span>{i.quantity}</span><button onClick={()=>change(i.id,1)}><Plus size={13}/></button></div></div><strong>${i.price*i.quantity}</strong></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>${subtotal}</strong></div><p>Shipping and taxes calculated at checkout.</p><button className="button primary checkout-button">Continue to checkout <ArrowRight size={16}/></button></div></>}</aside></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App />)
