import React,{useEffect,useMemo,useState} from 'react'
import {ArrowRight,Box,Check,Menu,Minus,Plus,Search,ShoppingCart,Sparkles,X} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {readCart,writeCart,cartCount,cartSubtotal,addCartItem,changeCartItem} from './cart.js'
import {products as fallbackProducts,categories as fallbackCategories} from './catalog.js'
import {getPublicCatalog,getCatalogCategories} from './api.js'
import './styles.css'

const faqs=[['How long does an order take?','Most standard projects are produced in a few business days. Custom projects can vary based on complexity.'],['Can you print a design I already have?','Absolutely. Upload your model during the custom project process and we can review it before production.'],['What materials and colors are available?','We offer a growing range of common 3D-printing materials, finishes, and colors depending on the project.']]

function App(){
 const [menuOpen,setMenuOpen]=useState(false),[cartOpen,setCartOpen]=useState(false),[cart,setCart]=useState(readCart),[category,setCategory]=useState('All'),[openFaq,setOpenFaq]=useState(0),[search,setSearch]=useState(''),[sort,setSort]=useState('featured'),[products,setProducts]=useState(fallbackProducts),[categories,setCategories]=useState(fallbackCategories),[catalogSource,setCatalogSource]=useState('local')
 useEffect(()=>{
  let cancelled=false
  Promise.all([getPublicCatalog(),getCatalogCategories()]).then(([remoteProducts,remoteCategories])=>{
   if(cancelled)return
   if(remoteProducts.length){setProducts(remoteProducts);setCatalogSource('FabOS')}
   if(remoteCategories.length)setCategories(['All',...remoteCategories.filter(c=>c&&c!=='All')])
  }).catch(()=>{})
  return()=>{cancelled=true}
 },[])
 const visible=useMemo(()=>{let list=category==='All'?products:products.filter(p=>p.category===category);const q=search.trim().toLowerCase();if(q)list=list.filter(p=>`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(q));if(sort==='price-low')list=[...list].sort((a,b)=>a.price-b.price);if(sort==='price-high')list=[...list].sort((a,b)=>b.price-a.price);if(sort==='name')list=[...list].sort((a,b)=>a.name.localeCompare(b.name));return list},[products,category,search,sort])
 const count=cartCount(cart),subtotal=cartSubtotal(cart)
 const add=p=>{const next=addCartItem(cart,{...p,quantity:1});setCart(next);writeCart(next);setCartOpen(true)}
 const change=(id,d)=>{const next=changeCartItem(cart,id,d);setCart(next);writeCart(next)}
 return <div className="site-shell"><header className="nav"><a className="brand" href="#top"><span className="brand-mark"><Box size={18}/></span><span>FAB<span>OS</span></span></a><nav className={menuOpen?'nav-links open':'nav-links'}><a href="#shop" onClick={()=>setMenuOpen(false)}>Shop</a><a href="/custom-work.html" onClick={()=>setMenuOpen(false)}>Custom Work</a><a href="/orders.html" onClick={()=>setMenuOpen(false)}>My Orders</a><a href="#process" onClick={()=>setMenuOpen(false)}>How It Works</a><a href="#about" onClick={()=>setMenuOpen(false)}>About</a></nav><div className="nav-actions"><a className="orders-nav-link" href="/orders.html">Orders</a><button className="cart" onClick={()=>setCartOpen(true)} aria-label={`Shopping cart, ${count} items`}><ShoppingCart size={19}/>{count>0&&<span>{count}</span>}</button><button className="menu-button" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle menu">{menuOpen?<X/>:<Menu/>}</button></div></header>
 <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> BUILT FOR REAL LIFE</p><h1>3D printed.<br/><em>Engineered</em> for you.</h1><p className="hero-text">Useful things, custom solutions, and one-off ideas brought to life with precision 3D printing.</p><div className="hero-buttons"><a className="button primary" href="#shop">Shop Projects <ArrowRight size={17}/></a><a className="button secondary" href="/custom-work.html">Need something custom?</a></div><div className="trust-row"><span><Check size={15}/> Made to order</span><span><Check size={15}/> Quality checked</span><span><Check size={15}/> Ships with care</span></div></div><div className="hero-object"><div className="object-ring ring-one"/><div className="object-ring ring-two"/><div className="floating-cube"><Box size={76}/></div><div className="object-label">PRECISION<br/><strong>MADE</strong></div></div></section>
 <section className="process" id="process"><div className="section-heading centered"><p className="eyebrow">HOW IT WORKS</p><h2>From idea to <em>finished part.</em></h2></div><div className="steps">{[['01','Choose or create','Pick a ready-to-print project or tell us what you need.'],['02','We make it real','We prepare, print, inspect, and finish your part.'],['03','It shows up','Your finished piece is packed carefully and shipped to you.']].map(([n,t,d])=><div className="step" key={n}><div className="step-number">{n}</div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
 <section className="shop-section" id="shop"><div className="section-heading"><p className="eyebrow">SHOP</p><h2>Things worth <em>printing.</em></h2><p>Start with something useful. Everything here is designed to be practical, durable, and good-looking.</p></div><div className="shop-tools"><label className="shop-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects..." aria-label="Search projects"/></label><label className="shop-sort"><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name</option></select></label></div><div className="category-row">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>{visible.length?<div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><a className="product-card-link" href={`/product.html?id=${p.id}`} aria-label={`Configure ${p.name}`}><div className="product-image"><div className="product-shape"><Box size={58}/></div><span>{p.tag||'Made to Order'}</span></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.description}</p></div><strong>${Number(p.price||0).toFixed(2)}</strong></div></a><button className="add-button" onClick={()=>add(p)}>Add to cart <Plus size={16}/></button></article>)}</div>:<div className="shop-empty"><Search size={26}/><h3>No projects found.</h3><p>{catalogSource==='FabOS'?'Try a different search or category.':'Start the FabOS API to load the live catalog, or try the local preview filters.'}</p><button className="button secondary" onClick={()=>{setSearch('');setCategory('All')}}>Clear filters</button></div>}</section>
 <section className="custom" id="custom"><div className="custom-panel"><div className="custom-copy"><p className="eyebrow">CUSTOM WORK</p><h2>Have an idea?<br/><em>Let's build it.</em></h2><p>From a replacement part to a completely original creation, custom printing is where we get to make something that doesn't exist yet.</p><a className="button light" href="/custom-work.html">Start a custom project <ArrowRight size={17}/></a></div><div className="custom-examples"><div className="example-main"><Box size={100}/><small>CUSTOM PANEL</small></div><div className="example-side"><div><Box size={30}/><span>Mounts</span></div><div><Box size={30}/><span>Enclosures</span></div><div><Box size={30}/><span>Brackets</span></div></div></div></div></section>
 <section className="about" id="about"><div><p className="eyebrow">WHY FABOS</p><h2>Not just a printer.<br/><em>A better way to make.</em></h2></div><div className="about-copy"><p>Good 3D printing isn't about pressing a button and hoping for the best. It's about choosing the right process, material, geometry, and finish for what the part actually needs to do.</p><p>That's the difference we bring to every order — whether it's a small desk accessory or a completely custom build.</p></div></section><section className="faq" id="contact"><div className="section-heading centered"><p className="eyebrow">QUESTIONS</p><h2>Before you <em>order.</em></h2></div>{faqs.map(([q,a],i)=><div className="faq-row" key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span>{openFaq===i?<Minus size={18}/>:<Plus size={18}/>}</button>{openFaq===i&&<p>{a}</p>}</div>)}</section></main>
 <footer><div className="brand"><span className="brand-mark"><Box size={17}/></span><span>FAB<span>OS</span></span></div><p>Useful things. Made better.</p><small>© 2026 FabOS. All rights reserved.</small></footer>
 {cartOpen&&<div className="cart-overlay" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">YOUR CART</p><h2>{count} {count===1?'item':'items'}</h2></div><button onClick={()=>setCartOpen(false)} aria-label="Close cart"><X/></button></div>{cart.length?<><div className="drawer-items">{cart.map(item=><div className="drawer-item" key={item.id}><div><strong>{item.name}</strong><span>${Number(item.price||0).toFixed(2)} each</span></div><div className="drawer-qty"><button onClick={()=>change(item.id,-1)}><Minus size={14}/></button><span>{item.quantity}</span><button onClick={()=>change(item.id,1)}><Plus size={14}/></button></div></div>)}</div><div className="drawer-total"><span>Subtotal</span><strong>${subtotal}</strong></div><a className="button primary full" href="/checkout.html">Checkout <ArrowRight size={16}/></a></>:<div className="empty-cart"><ShoppingCart size={28}/><p>Your cart is empty.</p><button className="button secondary" onClick={()=>setCartOpen(false)}>Continue shopping</button></div>}</aside></div>}</div>
}
createRoot(document.getElementById('root')).render(<App/>)
