import React,{useEffect,useState} from 'react'
import {ArrowLeft,ArrowRight,Box,ChevronDown,ShoppingBag} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {customerApi,AUTH_TOKEN_KEY} from './api.js'
import './styles.css'

const CUSTOMER_STATUS={new:'Order received',pending:'Order received',confirmed:'Order received',in_production:'Preparing your order',production:'Preparing your order',ready:'Final quality check',shipped:'Shipping',completed:'Delivered',cancelled:'Cancelled'}
function money(value){return `$${Number(value||0).toFixed(2)}`}
function statusLabel(value){return CUSTOMER_STATUS[String(value||'').toLowerCase()]||'Order received'}
function App(){
 const token=typeof localStorage!=='undefined'?localStorage.getItem(AUTH_TOKEN_KEY):''
 const [orders,setOrders]=useState([]),[open,setOpen]=useState(null),[loading,setLoading]=useState(Boolean(token)),[error,setError]=useState('')
 useEffect(()=>{if(!token){window.location.href='/account.html?return=orders';return}let cancelled=false;customerApi.orders().then(data=>{if(!cancelled)setOrders(data.orders||[])}).catch(err=>{if(!cancelled)setError(err.message||'Your order history is temporarily unavailable.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[token])
 if(!token||loading)return <div className="orders-shell"><main className="orders-empty"><h2>{loading?'Loading your orders…':'Opening your account…'}</h2></main></div>
 return <div className="orders-shell"><header className="orders-nav"><a className="orders-brand" href="/"><img className="brand-inline-mark" src="/brand/fabvex-mark.svg" alt="" /> FABVEX</a><nav><a href="/shop.html">Shop</a><a href="/custom-work.html">Custom Work</a></nav></header><main className="orders-main"><a className="orders-back" href="/"><ArrowLeft size={16}/> Back to home</a><section className="orders-hero"><p className="eyebrow">ORDER HISTORY</p><h1>Your orders.</h1><p>Your orders are loaded from your customer account.</p></section>{error?<section className="orders-empty"><h2>We couldn't load your orders.</h2><p>{error}</p><button className="button secondary" onClick={()=>window.location.reload()}>Try again</button></section>:orders.length?<section className="orders-list">{orders.map(order=>{const expanded=open===order.id;const created=order.created_at||order.createdAt;const orderNumber=order.order_number||order.orderNumber;const total=Number(order.total_cents||0)/100;const status=statusLabel(order.status);const cancelled=String(order.status||'').toLowerCase()==='cancelled';return <article className={`order-card ${cancelled?'cancelled':''}`} key={order.id||orderNumber}><button className="order-head" onClick={()=>setOpen(expanded?null:(order.id||orderNumber))} aria-expanded={expanded}><div><span className="order-number">{orderNumber}</span><strong>{created?new Date(created).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'}):'—'}</strong></div><div className="order-head-right"><span className="order-status">{status}</span><strong>{money(total)}</strong><ChevronDown className={expanded?'rotated':''} size={19}/></div></button>{expanded&&<div className="order-details"><p>{cancelled?'This order was cancelled.':'Order details are available on the order page.'}</p><a className="order-view-link" href={`/order.html?id=${encodeURIComponent(order.id)}`}>View order <ArrowRight size={15}/></a></div>}</article>})}</section>:<section className="orders-empty"><div><ShoppingBag size={32}/></div><h2>No orders yet.</h2><p>When you place an order, it will appear here in your account.</p><a className="button primary" href="/shop.html">Browse the collection <ArrowRight size={17}/></a></section>}</main></div>}
createRoot(document.getElementById('orders-root')).render(<App/>)
