import React,{useEffect,useState} from 'react'
import {ArrowLeft,ArrowRight,Check,Clock,FileText,XCircle} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {customerApi,AUTH_TOKEN_KEY} from './api.js'
import {getTheme,setTheme} from './theme.js'
import './styles.css'
import './quote.css'
function money(c){return '$'+(Number(c||0)/100).toFixed(2)}
const labels={draft:'Submitted',under_review:'Under review',sent:'Quote ready',accepted:'Accepted',declined:'Declined',expired:'Expired',approved:'Accepted'}
function App(){
 const token=typeof localStorage!=='undefined'?localStorage.getItem(AUTH_TOKEN_KEY):'',id=new URLSearchParams(location.search).get('id')||''
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(Boolean(token)),[action,setAction]=useState('')
 const load=()=>customerApi.quote(id).then(setData).catch(e=>setError(e.message||'Quote unavailable.')).finally(()=>setBusy(false))
 useEffect(()=>{if(!token){location.href='/account.html?return=/quote.html%3Fid='+encodeURIComponent(id);return}if(!id){setError('Quote not found.');setBusy(false);return}load()},[token,id])
 const decide=async decision=>{setAction(decision);setError('');try{const result=decision==='accept'?await customerApi.acceptQuote(id):await customerApi.declineQuote(id);if(result?.order_id)location.href='/order.html?id='+encodeURIComponent(result.order_id);else await load()}catch(e){setError(e.message||'We could not update the quote.')}finally{setAction('')}}
 if(busy)return <div className="quote-shell"><div className="quote-loading">Loading quote…</div></div>
 const quote=data?.quote,items=data?.items||[]
 if(error||!quote)return <div className="quote-shell"><main className="quote-main"><a href="/account.html"><ArrowLeft size={16}/> Back to account</a><div className="quote-missing"><XCircle size={32}/><h1>Quote unavailable.</h1><p>{error||'We could not find that quote in your account.'}</p></div></main></div>
 const status=String(quote.status||'draft').toLowerCase(),canDecide=status==='sent',canPay=status==='accepted'||status==='approved'
 return <div className="quote-shell"><header className="quote-nav"><a className="brand" href="/"><span className="brand-mark"><img src="/brand/fabvex-mark.svg" alt=""/></span><span>FAB<span>VEX</span></span></a><div><button className="quote-theme" onClick={()=>setTheme(getTheme()==='dark'?'light':'dark')}>Theme</button><a href="/account.html">My account</a></div></header><main className="quote-main"><a className="quote-back" href="/account.html"><ArrowLeft size={16}/> Back to account</a><section className="quote-hero"><div><p className="quote-kicker">QUOTE {quote.quote_number}</p><h1>{canDecide?'Your quote is ready.':'Your project is in progress.'}</h1><p>This is the current FABVEX quote for your project. Internal production information is not exposed here.</p></div><span className={'quote-status '+status}>{labels[status]||'In progress'}</span></section><div className="quote-grid"><section className="quote-panel"><div className="quote-panel-head"><div><span>QUOTE DETAILS</span><h2>What we're making</h2></div><FileText size={19}/></div><div className="quote-items">{items.map((item,i)=><div className="quote-item" key={item.id||i}><div><strong>{item.description||'Custom part'}</strong><small>{item.quantity} × {[item.material,item.color].filter(Boolean).join(' · ')||'Material to be determined'}</small></div><b>{money(Number(item.unit_price_cents||0)*Number(item.quantity||1))}</b></div>)}</div><div className="quote-total"><span>Total</span><strong>{money(quote.total_cents)}</strong></div>{quote.notes&&<div className="quote-notes"><span>PROJECT NOTES</span><p>{quote.notes}</p></div>}</section><section className="quote-panel"><div className="quote-panel-head"><div><span>WHAT HAPPENS NEXT</span><h2>Before production</h2></div><Clock size={19}/></div><ol className="quote-steps"><li className={status==='sent'?'current':''}><span>01</span><div><strong>You review the quote</strong><small>Confirm the price and scope match what you need.</small></div></li><li className={status==='accepted'||status==='approved'?'current':''}><span>02</span><div><strong>You accept it</strong><small>Acceptance turns the approved quote into the next order step.</small></div></li><li><span>03</span><div><strong>FABVEX prepares production</strong><small>Custom design/prototype work can require a separate proof approval.</small></div></li></ol>{error&&<p className="quote-error">{error}</p>}{canDecide&&<div className="quote-actions"><button className="quote-button accept" disabled={!!action} onClick={()=>decide('accept')}>{action==='accept'?'Accepting…':<>Accept Quote <Check size={16}/></>}</button><button className="quote-button decline" disabled={!!action} onClick={()=>decide('decline')}>{action==='decline'?'Declining…':<>Decline <XCircle size={16}/></>}</button></div>}{canPay&&<a className="quote-button accept" href="/orders.html">View my order <ArrowRight size={16}/></a>}</section></div></main></div>
}
createRoot(document.getElementById('quote-root')).render(<App/>)
