import React,{useMemo,useState} from 'react'
import {ArrowRight,Box,Search,ShoppingCart} from 'lucide-react'
import {createRoot} from 'react-dom/client'
import {readCart,cartCount} from './cart.js'
import {products,categories} from './catalog.js'
import './styles.css'

function App(){const [category,setCategory]=useState('All'),[search,setSearch]=useState(''),cart=readCart(),count=cartCount(cart);const list=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(search.toLowerCase().trim()))),[category,search]);return <div className="shop-page"><header><a className="shop-brand" href="/">FAB<span>OS</span></a><nav><a href="/">Home</a><a href="/custom-work.html">Custom Work</a><a href="/checkout.html">Cart {count?`(${count})`:''}</a></nav><a className="shop-cart" href="/checkout.html" aria-label={`Shopping cart, ${count} items`}><ShoppingCart size={19}/>{count>0&&<span>{count}</span>}</a></header><main><section className="shop-hero"><p className="eyebrow">THE COLLECTION</p><h1>Things worth <em>printing.</em></h1><p>Useful, made-to-order projects designed for desks, homes, and everyday setups.</p></section><div className="shop-controls"><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects..." aria-label="Search projects"/></label><div>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>{list.length?<div className="catalog">{list.map(p=><article key={p.id}><a href={`/product.html?id=${p.id}`} className="catalog-visual"><div><Box size={64}/></div><span>{p.tag}</span></a><div className="catalog-info"><div><small>{p.category}</small><h2>{p.name}</h2><p>{p.description}</p></div><strong>${p.price}</strong></div><a className="catalog-link" href={`/product.html?id=${p.id}`}>Configure <ArrowRight size={15}/></a></article>)}</div>:<div className="no-results"><h2>No projects found.</h2><p>Try another search or category.</p></div>}</main></div>}
createRoot(document.getElementById('shop-root')).render(<App/>)
